### ISSUE TITLE
Associatividade do Operador Ternário

### ISSUE THREAD

**Issue by theosirian** [lucasnanni/ilp2018#1]
Propomos a adição de um exemplo para exemplificar sua associatividade à direita:
```
id = a == 0 ? 10 : b == 0 ? 20 : 30
     -1------------------
                   -2--------------
```
A. Direita:
```
id = a == 0 ? 10 : (b == 0 ? 20 : 30)
```
A. Esquerda:
```
id = (a == 0 ? 10 : b == 0) ? 20 : 30
```

@theosirian
@gchicha

Pull Request: #2

**Comment by lucasnanni** [comment]
Exemplo adicionado à especificação da linguagem via merge do pull request #2 .
