### ISSUE TITLE
Falta de operador de negação ("!")

### ISSUE THREAD

**Issue by 0Cristofer** [lucasnanni/ilp2018#9]
Na especificação sintática, mais especificamente na seção de expressões, não há definição para o operador de negação. A precedência dele seria menor que a do operador "or" e sua associatividade seria à direita?

**Comment by lucasnanni** [comment]
Olá @0Cristofer, o operador de negação lógica ``!`` tem a mesma precedência e associatividade que o operador negativo unário. Adicionei o operador à tabela de operadores no commit 926827a644ec12eb2526957c5b91981a24b80af7. Obrigado pela ajuda!
